@TestTask.Server_HostAddress = http://localhost:5255

GET {{TestTask.Server_HostAddress}}/users/
Accept: application/json

###
PUT {{TestTask.Server_HostAddress}}/users/
Accept: application/json

###
PUT {{TestTask.Server_HostAddress}}/files/
Accept: multipart/form-data

###